name: Main workflow
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    paths:
      - setup.sh
      - action.yml
jobs:
  lint_shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ludeeus/action-shellcheck@master
  test_channel:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
        channel: [stable, beta, master]
    steps:
    - uses: actions/checkout@v3
    - id: flutter-action
      uses: ./
      with:
        channel: ${{ matrix.channel }}
    - name: Echo outputs
      run: |
        echo cache-path=${{ steps.flutter-action.outputs.cache-path }}
        echo cache-key=${{ steps.flutter-action.outputs.cache-key }}
        echo channel=${{ steps.flutter-action.outputs.channel }}
        echo version=${{ steps.flutter-action.outputs.version }}
        echo architecture=${{ steps.flutter-action.outputs.architecture }}
      shell: bash
    - run: dart --version
      shell: bash
    - run: flutter --version
      shell: bash
  test_cache:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        channel: stable
        cache: true
    - run: dart --version
      shell: bash
    - run: flutter --version
      shell: bash
  test_print_output:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - run: ./setup.sh -t -p                        | grep 'stable'
      shell: bash
    - run: ./setup.sh -t -p                        | grep '3.0.5'
      shell: bash
    - run: ./setup.sh -t -p                        | grep 'x64'
      shell: bash
    - run: ./setup.sh -t -p stable                 | grep 'stable'
      shell: bash
    - run: ./setup.sh -t -p beta                   | grep 'beta'
      shell: bash
    - run: ./setup.sh -t -p beta                   | grep '3.1.0-9.0.pre'
      shell: bash
    - run: ./setup.sh -t -p master                 | grep 'master'
      shell: bash
    - run: ./setup.sh -t -p -n 2 stable            | grep '2.10.5'
      shell: bash
    - run: ./setup.sh -t -p -n 2 beta              | grep '2.13.0-0.4.pre'
      shell: bash
    - run: ./setup.sh -t -p -n 2 any               | grep 'beta'
      shell: bash
    - run: ./setup.sh -t -p -n 2 any               | grep '2.13.0-0.4.pre'
      shell: bash
    - run: ./setup.sh -t -p -n 3 any               | grep 'stable'
      shell: bash
    - run: ./setup.sh -t -p -n 3 any               | grep '3.0.5'
      shell: bash
    - run: ./setup.sh -t -p -n 3 -a arm64 any      | grep 'arm64'
      shell: bash
    - run: ./setup.sh -t -p -n any -a arm64 stable | grep 'stable'
      shell: bash
    - run: ./setup.sh -t -p -n any -a arm64 stable | grep '3.0.5'
      shell: bash
    - run: ./setup.sh -t -p -n any -a arm64 stable | grep 'arm64'
      shell: bash
    - run: ./setup.sh -t -p -n 1 stable            | grep '1.22.6'
      shell: bash
    - run: ./setup.sh -t -p -n v1 stable           | grep 'v1.12.13+hotfix.9'
      shell: bash
    - run: ./setup.sh -t -p -n 0 any               | grep 'beta'
      shell: bash
    - run: ./setup.sh -t -p -n 0 any               | grep 'v0.11.13'
      shell: bash
    - run: ./setup.sh -t -p -n v0 any              | grep 'beta'
      shell: bash
    - run: ./setup.sh -t -p -n v0 any              | grep 'v0.11.13'
      shell: bash
    - run: ./setup.sh -t -p                        | grep 'flutter-macos-stable-3.0.5-x64-f1875d570e39de09040c8f79aa13cc56baab8db1'
      shell: bash
    - run: ./setup.sh -t -p stable                 | grep 'flutter-macos-stable-3.0.5-x64-f1875d570e39de09040c8f79aa13cc56baab8db1'
      shell: bash
    - run: ./setup.sh -t -p beta                   | grep 'flutter-macos-beta-3.1.0-9.0.pre-x64-f28e570c8cb12a004fae2d796d0d9cd46603bde9'
      shell: bash
    - run: ./setup.sh -t -p master                 | grep 'flutter-macos-master-master-x64-master'
      shell: bash
    - run: ./setup.sh -t -p -n 2 stable            | grep 'flutter-macos-stable-2.10.5-x64-5464c5bac742001448fe4fc0597be939379f88ea'
      shell: bash
    - run: ./setup.sh -t -p -n 2 beta              | grep 'flutter-macos-beta-2.13.0-0.4.pre-x64-25caf1461b8f643092a9f6f5b224453b5c057d10'
      shell: bash
    - run: ./setup.sh -t -p -n 2 any               | grep 'flutter-macos-beta-2.13.0-0.4.pre-x64-25caf1461b8f643092a9f6f5b224453b5c057d10'
      shell: bash
    - run: ./setup.sh -t -p -n 3 any               | grep 'flutter-macos-stable-3.0.5-x64-f1875d570e39de09040c8f79aa13cc56baab8db1'
      shell: bash
    - run: ./setup.sh -t -p -n 3 -a arm64 any      | grep 'flutter-macos-stable-3.0.5-arm64-f1875d570e39de09040c8f79aa13cc56baab8db1'
      shell: bash
    - run: ./setup.sh -t -p -n any -a arm64 stable | grep 'flutter-macos-stable-3.0.5-arm64-f1875d570e39de09040c8f79aa13cc56baab8db1'
      shell: bash
    - run: ./setup.sh -t -p -n 1 stable            | grep 'flutter-macos-stable-1.22.6-x64-9b2d32b605630f28625709ebd9d78ab3016b2bf6'
      shell: bash
    - run: ./setup.sh -t -p -n v1 stable           | grep 'flutter-macos-stable-v1.12.13+hotfix.9-x64-f139b11009aeb8ed2a3a3aa8b0066e482709dde3'
      shell: bash
    - run: ./setup.sh -t -p -n 0 any               | grep 'flutter-macos-beta-v0.11.13-x64-58c8489fcdb4e4ef6c010117584c9b23d15221aa'
      shell: bash
    - run: ./setup.sh -t -p -n v0 any              | grep 'flutter-macos-beta-v0.11.13-x64-58c8489fcdb4e4ef6c010117584c9b23d15221aa'
      shell: bash
    - run: ./setup.sh -t -p                        | grep '/Users/runner/work/_temp/flutter/stable-3.0.5-x64'
      shell: bash
    - run: ./setup.sh -t -p stable                 | grep '/Users/runner/work/_temp/flutter/stable-3.0.5-x64'
      shell: bash
    - run: ./setup.sh -t -p beta                   | grep '/Users/runner/work/_temp/flutter/beta-3.1.0-9.0.pre-x64'
      shell: bash
    - run: ./setup.sh -t -p master                 | grep '/Users/runner/work/_temp/flutter/master-master-x64'
      shell: bash
    - run: ./setup.sh -t -p -k 'custom-:channel:-:version:-:hash:'       | grep 'custom-stable-3.0.5-f1875d570e39de09040c8f79aa13cc56baab8db1'
      shell: bash
    - run: ./setup.sh -t -p -k 'custom-:channel:-:version:-:sha256:'     | grep 'custom-stable-3.0.5-e79a04dcfd1b583e5831433fc200800ba0d1e9fe4567cb661479bd2542d4c685'
      shell: bash
    - run: ./setup.sh -t -p -c '/tmp/flutter/:channel:-:version:-:hash:' | grep '/tmp/flutter/stable-3.0.5-f1875d570e39de09040c8f79aa13cc56baab8db1'
      shell: bash
